<?php

use Illuminate\Database\Seeder;

class AddChargeDetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data[] = ["id" => 1,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 2.72,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 2,"name" => "Address Correction","code" => "COR","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 6.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 3,"name" => "Extended Area Surcharge","code" => "EAS","weight_rate" => 0.34,"package_rate" => 0,"consignment_rate" => 0,"min" => 17.8,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 4,"name" => "Large Package","code" => "LPS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 5,"name" => "Over Max Limits","code" => "MAX","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 45,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 6,"name" => "Remote Area Surcharge","code" => "RAS","weight_rate" => 0.43,"package_rate" => 0,"consignment_rate" => 0,"min" => 22.5,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 7,"name" => "Residential Surcharge","code" => "RES","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 1.19,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 1,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 8,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 10,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 2,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 9,"name" => "Address Correction","code" => "COR","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 4.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 2,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 10,"name" => "Extended Area Surcharge","code" => "EAS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 2,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 11,"name" => "Over Size Piece","code" => "OSP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 2,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 12,"name" => "Over Weight Piece","code" => "OWP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 2,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 13,"name" => "Insurance","code" => "INS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 1.5,"min" => 12,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 2,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 14,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 10,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 15,"name" => "Address Correction","code" => "COR","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 9,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 16,"name" => "Dangerous Goods","code" => "IDG","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 64,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 17,"name" => "Dangerous Goods","code" => "ADG","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 64,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 18,"name" => "DG (Excepted Qty)","code" => "EQT","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 4,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 19,"name" => "Dry Ice","code" => "ICE","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 20,"name" => "Duties & Taxes Paid","code" => "DTP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 21,"name" => "Handover to Broker","code" => "BRO","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 25,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 22,"name" => "Out of Area Surcharge","code" => "OOA","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 23,"name" => "Over Size Piece","code" => "OSP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 24,"name" => "Over Weight Piece","code" => "OWP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 25,"name" => "Insurance","code" => "INS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 1.5,"min" => 12,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 3,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 26,"name" => "Address Correction","code" => "COR","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 5.72,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 4,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 27,"name" => "DG (Accessible)","code" => "ADG","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 52,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 4,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 28,"name" => "DG (Inaccessible)","code" => "IDG","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 4,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 29,"name" => "Extended Area Surcharge","code" => "EAS","weight_rate" => 0.31,"package_rate" => 0,"consignment_rate" => 0,"min" => 14,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 4,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 30,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 31,"name" => "Large Package","code" => "LPS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 32,"name" => "Out of Area Surcharge","code" => "OOA","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 33,"name" => "Over Max Limits","code" => "MAX","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 45,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 34,"name" => "Over Size Piece","code" => "OSP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 35,"name" => "Over Weight Piece","code" => "OWP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 36,"name" => "Remote Area Surcharge","code" => "RAS","weight_rate" => 0.35,"package_rate" => 0,"consignment_rate" => 0,"min" => 15,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 37,"name" => "Residential Delivery","code" => "RES","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 2.83,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 38,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 39,"name" => "Address Correction","code" => "COR","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 40,"name" => "DG (Accessible)","code" => "ADG","weight_rate" => 0.85,"package_rate" => 0,"consignment_rate" => 57,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 41,"name" => "DG (Excepted Qty)","code" => "EQT","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 42,"name" => "DG (Inaccessible)","code" => "IDG","weight_rate" => 0.58,"package_rate" => 0,"consignment_rate" => 40,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 43,"name" => "Dry Ice","code" => "ICE","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 12.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 44,"name" => "Duties & Taxes Paid","code" => "DTP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 45,"name" => "Extended Area Surcharge","code" => "EAS","weight_rate" => 0.35,"package_rate" => 0,"consignment_rate" => 0,"min" => 15,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 46,"name" => "Handover to Broker","code" => "BRO","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 47,"name" => "Large Package","code" => "LPS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 48,"name" => "Out of Area Surcharge","code" => "OOA","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 49,"name" => "Over Max Limits","code" => "MAX","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 45,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 50,"name" => "Over Size Piece","code" => "OSP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 51,"name" => "Over Weight Piece","code" => "OWP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 7.5,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 52,"name" => "Remote Area Surcharge","code" => "RAS","weight_rate" => 0.35,"package_rate" => 0,"consignment_rate" => 0,"min" => 15,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 53,"name" => "Residential Delivery","code" => "RES","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 2.83,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 11,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 54,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 55,"name" => "Large Package","code" => "LPS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 38.95,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 56,"name" => "Out of Area Surcharge","code" => "OOA","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 57,"name" => "Over Max Limits","code" => "MAX","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 50.09,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 58,"name" => "Over Size Piece","code" => "OSP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 59,"name" => "Over Weight Piece","code" => "OWP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 60,"name" => "Remote Area Surcharge","code" => "RAD","weight_rate" => 0.39,"package_rate" => 0,"consignment_rate" => 0,"min" => 16.7,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 61,"name" => "Residential Delivery","code" => "RES","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 3.15,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 12,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 62,"name" => "Additional Handling","code" => "ADH","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 63,"name" => "Address Correction","code" => "COR","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 64,"name" => "DG (Accessible)","code" => "ADG","weight_rate" => 0.95,"package_rate" => 0,"consignment_rate" => 63.47,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 65,"name" => "DG (Excepted Qty)","code" => "EQT","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 66,"name" => "DG (Inaccessible)","code" => "IDG","weight_rate" => 0.58,"package_rate" => 0,"consignment_rate" => 44.55,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 67,"name" => "Dry Ice","code" => "ICE","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 13.92,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 68,"name" => "Duties & Taxes Paid","code" => "DTP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 69,"name" => "Extended Area Surcharge","code" => "EAS","weight_rate" => 0.4,"package_rate" => 0,"consignment_rate" => 0,"min" => 16.7,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 70,"name" => "Handover to Broker","code" => "BRO","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 38.95,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 71,"name" => "Large Package","code" => "LPS","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 38.95,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 72,"name" => "Out of Area Surcharge","code" => "OOA","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 73,"name" => "Over Max Limits","code" => "MAX","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 50.09,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 74,"name" => "Over Size Piece","code" => "OSP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 75,"name" => "Over Weight Piece","code" => "OWP","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 8.35,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 76,"name" => "Remote Area Surcharge","code" => "RAS","weight_rate" => 0.39,"package_rate" => 0,"consignment_rate" => 0,"min" => 16.7,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 77,"name" => "Residential Delivery","code" => "RES","weight_rate" => 0,"package_rate" => 0,"consignment_rate" => 3.15,"min" => 0,"company_id" => 0,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 13,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 78,"name" => "Oversize Piece","code" => "OSP","weight_rate" => 5,"package_rate" => 0,"consignment_rate" => 0,"min" => 0,"company_id" => 122,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 79,"name" => "Oversize Piece","code" => "OSP","weight_rate" => 4,"package_rate" => 0,"consignment_rate" => 0,"min" => 0,"company_id" => 774,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 80,"name" => "Extended Area Delivery","code" => "EAD","weight_rate" => 0.38,"package_rate" => 0,"consignment_rate" => 0,"min" => 20,"company_id" => 827,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 81,"name" => "Oversize Piece","code" => "OSP","weight_rate" => 5,"package_rate" => 0,"consignment_rate" => 0,"min" => 0,"company_id" => 827,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 82,"name" => "Remote Area Surcharge","code" => "RAS","weight_rate" => 0.45,"package_rate" => 0,"consignment_rate" => 0,"min" => 24,"company_id" => 827,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];
        $data[] = ["id" => 83,"name" => "Residential Delivery","code" => "RES","weight_rate" => 2.75,"package_rate" => 0,"consignment_rate" => 0,"min" => 0,"company_id" => 827,"from_date" => "2018-01-01","to_date" => "2099-12-31","add_charge_id" => 10,"created_at" => null,"updated_at" => null];

        // Modify a few records
        DB::table('add_charge_details')->insert($data);
    }
}
