<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country' => 'ANDORRA',
                'country_code' => 'AD',
                'alpha' => 'AND',
                'iso' => 20,
                'eu' => 0,
            'postal_validation' => '/^([A-Z]{2}[0-9]{3})$/i',
                'postcode_example' => 'AB123',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'country' => 'UAE',
                'country_code' => 'AE',
                'alpha' => 'ARE',
                'iso' => 784,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AED',
                'fedex_route' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'country' => 'ANTIGUA',
                'country_code' => 'AG',
                'alpha' => 'ATG',
                'iso' => 28,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'country' => 'ANGUILLA',
                'country_code' => 'AI',
                'alpha' => 'AIA',
                'iso' => 660,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'country' => 'ALBANIA',
                'country_code' => 'AL',
                'alpha' => 'ALB',
                'iso' => 8,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'ALL',
                'fedex_route' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'country' => 'ARMENIA',
                'country_code' => 'AM',
                'alpha' => 'ARM',
                'iso' => 51,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'AMD',
                'fedex_route' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'country' => 'NL ANTILLES',
                'country_code' => 'AN',
                'alpha' => 'ANT',
                'iso' => 530,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => '',
                'fedex_route' => 2,
            ),
            7 => 
            array (
                'id' => 8,
                'country' => 'ANGOLA',
                'country_code' => 'AO',
                'alpha' => 'AGO',
                'iso' => 24,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AOA',
                'fedex_route' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'country' => 'ARGENTINA',
                'country_code' => 'AR',
                'alpha' => 'ARG',
                'iso' => 32,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'ARS',
                'fedex_route' => 2,
            ),
            9 => 
            array (
                'id' => 10,
                'country' => 'AMERICAN SAMOA',
                'country_code' => 'AS',
                'alpha' => 'ASM',
                'iso' => 16,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'country' => 'AUSTRIA',
                'country_code' => 'AT',
                'alpha' => 'AUT',
                'iso' => 40,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'country' => 'AUSTRALIA',
                'country_code' => 'AU',
                'alpha' => 'AUS',
                'iso' => 36,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'AUD',
                'fedex_route' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'country' => 'ARUBA',
                'country_code' => 'AW',
                'alpha' => 'ABW',
                'iso' => 533,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AWG',
                'fedex_route' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'country' => 'AZERBAIJAN',
                'country_code' => 'AZ',
                'alpha' => 'AZE',
                'iso' => 31,
                'eu' => 0,
            'postal_validation' => '/^([A-Z]{2}[0-9]{4})$/i',
                'postcode_example' => 'AB1234',
                'currency_code' => 'AZN',
                'fedex_route' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'country' => 'BARBADOS',
                'country_code' => 'BB',
                'alpha' => 'BRB',
                'iso' => 52,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BBD',
                'fedex_route' => 2,
            ),
            15 => 
            array (
                'id' => 16,
                'country' => 'BANGLADESH',
                'country_code' => 'BD',
                'alpha' => 'BGD',
                'iso' => 50,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'BDT',
                'fedex_route' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'country' => 'BELGIUM',
                'country_code' => 'BE',
                'alpha' => 'BEL',
                'iso' => 56,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'country' => 'BURKINAFASO',
                'country_code' => 'BF',
                'alpha' => 'BFA',
                'iso' => 854,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'country' => 'BULGARIA',
                'country_code' => 'BG',
                'alpha' => 'BGR',
                'iso' => 100,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'BGN',
                'fedex_route' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'country' => 'BAHRAIN',
                'country_code' => 'BH',
                'alpha' => 'BHR',
                'iso' => 48,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BHD',
                'fedex_route' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'country' => 'BURUNDI',
                'country_code' => 'BI',
                'alpha' => 'BDI',
                'iso' => 108,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BIF',
                'fedex_route' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'country' => 'BENIN',
                'country_code' => 'BJ',
                'alpha' => 'BEN',
                'iso' => 204,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'country' => 'BERMUDA',
                'country_code' => 'BM',
                'alpha' => 'BMU',
                'iso' => 60,
                'eu' => 0,
            'postal_validation' => '/^([A-Z]{2}[0-9]{2})$/i',
                'postcode_example' => 'AB12',
                'currency_code' => 'BMD',
                'fedex_route' => 2,
            ),
            23 => 
            array (
                'id' => 24,
                'country' => 'BRUNEI',
                'country_code' => 'BN',
                'alpha' => 'BRN',
                'iso' => 96,
                'eu' => 0,
            'postal_validation' => '/^([A-Z]{2}[0-9]{4})$/i',
                'postcode_example' => 'AB1234',
                'currency_code' => 'BND',
                'fedex_route' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'country' => 'BOLIVIA',
                'country_code' => 'BO',
                'alpha' => 'BOL',
                'iso' => 68,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BOB',
                'fedex_route' => 2,
            ),
            25 => 
            array (
                'id' => 26,
                'country' => 'BRAZIL',
                'country_code' => 'BR',
                'alpha' => 'BRA',
                'iso' => 76,
                'eu' => 0,
                'postal_validation' => '/^\\d{5}-?\\d{3}$/',
                'postcode_example' => '12345-12',
                'currency_code' => 'BRL',
                'fedex_route' => 2,
            ),
            26 => 
            array (
                'id' => 27,
                'country' => 'BAHAMAS',
                'country_code' => 'BS',
                'alpha' => 'BHS',
                'iso' => 44,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BSD',
                'fedex_route' => 2,
            ),
            27 => 
            array (
                'id' => 28,
                'country' => 'BHUTAN',
                'country_code' => 'BT',
                'alpha' => 'BTN',
                'iso' => 64,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'INR',
                'fedex_route' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'country' => 'BOTSWANA',
                'country_code' => 'BW',
                'alpha' => 'BWA',
                'iso' => 72,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BWP',
                'fedex_route' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'country' => 'BELARUS',
                'country_code' => 'BY',
                'alpha' => 'BLR',
                'iso' => 112,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'BYR',
                'fedex_route' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'country' => 'BELIZE',
                'country_code' => 'BZ',
                'alpha' => 'BLZ',
                'iso' => 84,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'BZD',
                'fedex_route' => 2,
            ),
            31 => 
            array (
                'id' => 32,
                'country' => 'CANADA',
                'country_code' => 'CA',
                'alpha' => 'CAN',
                'iso' => 124,
                'eu' => 0,
            'postal_validation' => '/^[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJKLMNPRSTVWXYZ]( )?\\d[ABCEGHJKLMNPRSTVWXYZ]\\d$/i',
                'postcode_example' => '',
                'currency_code' => 'CAD',
                'fedex_route' => 2,
            ),
            32 => 
            array (
                'id' => 33,
                'country' => 'DEM. REP. OF CONGO',
                'country_code' => 'CD',
                'alpha' => 'COD',
                'iso' => 180,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => '',
                'fedex_route' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'country' => 'CENTAFRREP',
                'country_code' => 'CF',
                'alpha' => 'CAF',
                'iso' => 140,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XAF',
                'fedex_route' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'country' => 'CONGOBRAZZAVILLE',
                'country_code' => 'CG',
                'alpha' => 'COG',
                'iso' => 178,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XAF',
                'fedex_route' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'country' => 'SWITZERLAND',
                'country_code' => 'CH',
                'alpha' => 'CHE',
                'iso' => 756,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'CHF',
                'fedex_route' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'country' => 'IVORYCOAST',
                'country_code' => 'CI',
                'alpha' => 'CIV',
                'iso' => 384,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'country' => 'COOK ISLANDS',
                'country_code' => 'CK',
                'alpha' => 'COK',
                'iso' => 184,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'NZD',
                'fedex_route' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'country' => 'CHILE',
                'country_code' => 'CL',
                'alpha' => 'CHL',
                'iso' => 152,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{7}$/i',
                'postcode_example' => '1234567',
                'currency_code' => 'CLP',
                'fedex_route' => 2,
            ),
            39 => 
            array (
                'id' => 40,
                'country' => 'CAMEROON',
                'country_code' => 'CM',
                'alpha' => 'CMR',
                'iso' => 120,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XAF',
                'fedex_route' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'country' => 'CHINA',
                'country_code' => 'CN',
                'alpha' => 'CHN',
                'iso' => 156,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'CNY',
                'fedex_route' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'country' => 'COLOMBIA',
                'country_code' => 'CO',
                'alpha' => 'COL',
                'iso' => 170,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'COP',
                'fedex_route' => 2,
            ),
            42 => 
            array (
                'id' => 43,
                'country' => 'COSTA RICA',
                'country_code' => 'CR',
                'alpha' => 'CRI',
                'iso' => 188,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'CRC',
                'fedex_route' => 2,
            ),
            43 => 
            array (
                'id' => 44,
                'country' => 'CAPEVERDE',
                'country_code' => 'CV',
                'alpha' => 'CPV',
                'iso' => 132,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'CVE',
                'fedex_route' => 1,
            ),
            44 => 
            array (
                'id' => 45,
                'country' => 'CYPRUS',
                'country_code' => 'CY',
                'alpha' => 'CYP',
                'iso' => 196,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            45 => 
            array (
                'id' => 46,
                'country' => 'CZECH REPUBLIC',
                'country_code' => 'CZ',
                'alpha' => 'CZE',
                'iso' => 203,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'CZK',
                'fedex_route' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'country' => 'GERMANY',
                'country_code' => 'DE',
                'alpha' => 'DEU',
                'iso' => 276,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'country' => 'DJIBOUTI',
                'country_code' => 'DJ',
                'alpha' => 'DJI',
                'iso' => 262,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'DJF',
                'fedex_route' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'country' => 'DENMARK',
                'country_code' => 'DK',
                'alpha' => 'DNK',
                'iso' => 208,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'DKK',
                'fedex_route' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'country' => 'DOMINICA',
                'country_code' => 'DM',
                'alpha' => 'DMA',
                'iso' => 212,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            50 => 
            array (
                'id' => 51,
                'country' => 'DOMINICAN REPUBLIC',
                'country_code' => 'DO',
                'alpha' => 'DOM',
                'iso' => 214,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'DOP',
                'fedex_route' => 2,
            ),
            51 => 
            array (
                'id' => 52,
                'country' => 'ALGERIA',
                'country_code' => 'DZ',
                'alpha' => 'DZA',
                'iso' => 12,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'DZD',
                'fedex_route' => 1,
            ),
            52 => 
            array (
                'id' => 53,
                'country' => 'ECUADOR',
                'country_code' => 'EC',
                'alpha' => 'ECU',
                'iso' => 218,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            53 => 
            array (
                'id' => 54,
                'country' => 'ESTONIA',
                'country_code' => 'EE',
                'alpha' => 'EST',
                'iso' => 233,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            54 => 
            array (
                'id' => 55,
                'country' => 'EGYPT',
                'country_code' => 'EG',
                'alpha' => 'EGY',
                'iso' => 818,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EGP',
                'fedex_route' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'country' => 'ERITREA',
                'country_code' => 'ER',
                'alpha' => 'ERI',
                'iso' => 232,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'ERN',
                'fedex_route' => 1,
            ),
            56 => 
            array (
                'id' => 57,
            'country' => 'SPAIN (MAINLAND ONLY)',
                'country_code' => 'ES',
                'alpha' => 'ESP',
                'iso' => 724,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'country' => 'ETHIOPIA',
                'country_code' => 'ET',
                'alpha' => 'ETH',
                'iso' => 231,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'ETB',
                'fedex_route' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'country' => 'FINLAND',
                'country_code' => 'FI',
                'alpha' => 'FIN',
                'iso' => 246,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'country' => 'FIJI',
                'country_code' => 'FJ',
                'alpha' => 'FJI',
                'iso' => 242,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'FJD',
                'fedex_route' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'country' => 'MICRONESIA',
                'country_code' => 'FM',
                'alpha' => 'FSM',
                'iso' => 583,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'country' => 'FAROE ISLANDS',
                'country_code' => 'FO',
                'alpha' => 'FRO',
                'iso' => 234,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '100',
                'currency_code' => 'DKK',
                'fedex_route' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'country' => 'FRANCE',
                'country_code' => 'FR',
                'alpha' => 'FRA',
                'iso' => 250,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'country' => 'GABON',
                'country_code' => 'GA',
                'alpha' => 'GAB',
                'iso' => 266,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XAF',
                'fedex_route' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'country' => 'UNITED KINGDOM',
                'country_code' => 'GB',
                'alpha' => 'GBR',
                'iso' => 826,
                'eu' => 1,
                'postal_validation' => '/[A-Z]{1,2}[0-9][0-9A-Z]?\\s?[0-9][A-Z]{2}/',
                'postcode_example' => 'BT41 2NQ',
                'currency_code' => 'GBP',
                'fedex_route' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'country' => 'GRENADA',
                'country_code' => 'GD',
                'alpha' => 'GRD',
                'iso' => 308,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            66 => 
            array (
                'id' => 67,
                'country' => 'GEORGIA',
                'country_code' => 'GE',
                'alpha' => 'GEO',
                'iso' => 268,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'GEL',
                'fedex_route' => 1,
            ),
            67 => 
            array (
                'id' => 68,
                'country' => 'FRENCH GUIANA',
                'country_code' => 'GF',
                'alpha' => 'GUF',
                'iso' => 254,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 2,
            ),
            68 => 
            array (
                'id' => 69,
                'country' => 'GHANA',
                'country_code' => 'GH',
                'alpha' => 'GHA',
                'iso' => 288,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'GHS',
                'fedex_route' => 1,
            ),
            69 => 
            array (
                'id' => 70,
                'country' => 'GIBRALTAR',
                'country_code' => 'GI',
                'alpha' => 'GIB',
                'iso' => 292,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'GIP',
                'fedex_route' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'country' => 'GREENLAND',
                'country_code' => 'GL',
                'alpha' => 'GRL',
                'iso' => 304,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'DKK',
                'fedex_route' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'country' => 'GAMBIA',
                'country_code' => 'GM',
                'alpha' => 'GMB',
                'iso' => 270,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'GMD',
                'fedex_route' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'country' => 'GUINEA',
                'country_code' => 'GN',
                'alpha' => 'GIN',
                'iso' => 324,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '123',
                'currency_code' => 'GNF',
                'fedex_route' => 1,
            ),
            73 => 
            array (
                'id' => 74,
                'country' => 'GUADELOUPE',
                'country_code' => 'GP',
                'alpha' => 'GLP',
                'iso' => 312,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 2,
            ),
            74 => 
            array (
                'id' => 75,
                'country' => 'EQUATORIAL GUINEA',
                'country_code' => 'GQ',
                'alpha' => 'GNQ',
                'iso' => 226,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XAF',
                'fedex_route' => 1,
            ),
            75 => 
            array (
                'id' => 76,
                'country' => 'GREECE',
                'country_code' => 'GR',
                'alpha' => 'GRC',
                'iso' => 300,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'country' => 'GUATEMALA',
                'country_code' => 'GT',
                'alpha' => 'GTM',
                'iso' => 320,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'GTQ',
                'fedex_route' => 2,
            ),
            77 => 
            array (
                'id' => 78,
                'country' => 'GUAM',
                'country_code' => 'GU',
                'alpha' => 'GUM',
                'iso' => 316,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            78 => 
            array (
                'id' => 79,
                'country' => 'GUINEABISSAU',
                'country_code' => 'GW',
                'alpha' => 'GNB',
                'iso' => 624,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'country' => 'GUYANA',
                'country_code' => 'GY',
                'alpha' => 'GUY',
                'iso' => 328,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'GYD',
                'fedex_route' => 2,
            ),
            80 => 
            array (
                'id' => 81,
                'country' => 'HONGKONG',
                'country_code' => 'HK',
                'alpha' => 'HKG',
                'iso' => 344,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'HKD',
                'fedex_route' => 1,
            ),
            81 => 
            array (
                'id' => 82,
                'country' => 'HONDURAS',
                'country_code' => 'HN',
                'alpha' => 'HND',
                'iso' => 340,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'HNL',
                'fedex_route' => 2,
            ),
            82 => 
            array (
                'id' => 83,
                'country' => 'CROATIA',
                'country_code' => 'HR',
                'alpha' => 'HRV',
                'iso' => 191,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'HRK',
                'fedex_route' => 1,
            ),
            83 => 
            array (
                'id' => 84,
                'country' => 'HAITI',
                'country_code' => 'HT',
                'alpha' => 'HTI',
                'iso' => 332,
                'eu' => 0,
                'postal_validation' => '/^[A-Z]{2}[0-9]{4}$/i',
                'postcode_example' => 'AB1234',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            84 => 
            array (
                'id' => 85,
                'country' => 'HUNGARY',
                'country_code' => 'HU',
                'alpha' => 'HUN',
                'iso' => 348,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'HUF',
                'fedex_route' => 1,
            ),
            85 => 
            array (
                'id' => 86,
                'country' => 'INDONESIA',
                'country_code' => 'ID',
                'alpha' => 'IDN',
                'iso' => 360,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'IDR',
                'fedex_route' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'country' => 'IRELAND',
                'country_code' => 'IE',
                'alpha' => 'IRL',
                'iso' => 372,
                'eu' => 1,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            87 => 
            array (
                'id' => 88,
                'country' => 'ISRAEL',
                'country_code' => 'IL',
                'alpha' => 'ISR',
                'iso' => 376,
                'eu' => 0,
            'postal_validation' => '/(^[0-9]{7}$)/i',
                'postcode_example' => '1234567',
                'currency_code' => 'ILS',
                'fedex_route' => 1,
            ),
            88 => 
            array (
                'id' => 89,
                'country' => 'INDIA',
                'country_code' => 'IN',
                'alpha' => 'IND',
                'iso' => 356,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'INR',
                'fedex_route' => 1,
            ),
            89 => 
            array (
                'id' => 90,
                'country' => 'ICELAND',
                'country_code' => 'IS',
                'alpha' => 'ISL',
                'iso' => 352,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '123',
                'currency_code' => 'ISK',
                'fedex_route' => 1,
            ),
            90 => 
            array (
                'id' => 91,
                'country' => 'ITALY',
                'country_code' => 'IT',
                'alpha' => 'ITA',
                'iso' => 380,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            91 => 
            array (
                'id' => 92,
                'country' => 'JAMAICA',
                'country_code' => 'JM',
                'alpha' => 'JAM',
                'iso' => 388,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'JMD',
                'fedex_route' => 2,
            ),
            92 => 
            array (
                'id' => 93,
                'country' => 'JORDAN',
                'country_code' => 'JO',
                'alpha' => 'JOR',
                'iso' => 400,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'JOD',
                'fedex_route' => 1,
            ),
            93 => 
            array (
                'id' => 94,
                'country' => 'JAPAN',
                'country_code' => 'JP',
                'alpha' => 'JPN',
                'iso' => 392,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}\\-[0-9]{4}$/i',
                'postcode_example' => '154-0023',
                'currency_code' => 'JPY',
                'fedex_route' => 1,
            ),
            94 => 
            array (
                'id' => 95,
                'country' => 'KENYA',
                'country_code' => 'KE',
                'alpha' => 'KEN',
                'iso' => 404,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'KES',
                'fedex_route' => 1,
            ),
            95 => 
            array (
                'id' => 96,
                'country' => 'KYRGYZSTAN',
                'country_code' => 'KG',
                'alpha' => 'KGZ',
                'iso' => 417,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'KGS',
                'fedex_route' => 1,
            ),
            96 => 
            array (
                'id' => 97,
                'country' => 'CAMBODIA',
                'country_code' => 'KH',
                'alpha' => 'KHM',
                'iso' => 116,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'KHR',
                'fedex_route' => 1,
            ),
            97 => 
            array (
                'id' => 98,
                'country' => 'STKITTS&NEVIS',
                'country_code' => 'KN',
                'alpha' => 'KNA',
                'iso' => 659,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            98 => 
            array (
                'id' => 99,
                'country' => 'SOUTH KOREA',
                'country_code' => 'KR',
                'alpha' => 'KOR',
                'iso' => 410,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '11010',
                'currency_code' => 'KRW',
                'fedex_route' => 1,
            ),
            99 => 
            array (
                'id' => 100,
                'country' => 'KUWAIT',
                'country_code' => 'KW',
                'alpha' => 'KWT',
                'iso' => 414,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'KWD',
                'fedex_route' => 1,
            ),
            100 => 
            array (
                'id' => 101,
                'country' => 'CAYMANISLANDS',
                'country_code' => 'KY',
                'alpha' => 'CYM',
                'iso' => 136,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'KYD',
                'fedex_route' => 2,
            ),
            101 => 
            array (
                'id' => 102,
                'country' => 'KAZAKHSTAN',
                'country_code' => 'KZ',
                'alpha' => 'KAZ',
                'iso' => 398,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'KZT',
                'fedex_route' => 1,
            ),
            102 => 
            array (
                'id' => 103,
                'country' => 'LAOS',
                'country_code' => 'LA',
                'alpha' => 'LAO',
                'iso' => 418,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'LAK',
                'fedex_route' => 1,
            ),
            103 => 
            array (
                'id' => 104,
                'country' => 'LEBANON',
                'country_code' => 'LB',
                'alpha' => 'LBN',
                'iso' => 422,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'LBP',
                'fedex_route' => 1,
            ),
            104 => 
            array (
                'id' => 105,
                'country' => 'ST LUCIA',
                'country_code' => 'LC',
                'alpha' => 'LCA',
                'iso' => 662,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            105 => 
            array (
                'id' => 106,
                'country' => 'LIECHTENSTEIN',
                'country_code' => 'LI',
                'alpha' => 'LIE',
                'iso' => 438,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'CHF',
                'fedex_route' => 1,
            ),
            106 => 
            array (
                'id' => 107,
                'country' => 'SRI LANKA',
                'country_code' => 'LK',
                'alpha' => 'LKA',
                'iso' => 144,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'LKR',
                'fedex_route' => 1,
            ),
            107 => 
            array (
                'id' => 108,
                'country' => 'LIBERIA',
                'country_code' => 'LR',
                'alpha' => 'LBR',
                'iso' => 430,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'LRD',
                'fedex_route' => 1,
            ),
            108 => 
            array (
                'id' => 109,
                'country' => 'LESOTHO',
                'country_code' => 'LS',
                'alpha' => 'LSO',
                'iso' => 426,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '123',
                'currency_code' => 'ZAR',
                'fedex_route' => 1,
            ),
            109 => 
            array (
                'id' => 110,
                'country' => 'LITHUANIA',
                'country_code' => 'LT',
                'alpha' => 'LTU',
                'iso' => 440,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => 'LT-04340',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            110 => 
            array (
                'id' => 111,
                'country' => 'LUXEMBOURG',
                'country_code' => 'LU',
                'alpha' => 'LUX',
                'iso' => 442,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            111 => 
            array (
                'id' => 112,
                'country' => 'LATVIA',
                'country_code' => 'LV',
                'alpha' => 'LVA',
                'iso' => 428,
                'eu' => 1,
                'postal_validation' => '/^LV-[0-9]{4}$/i',
                'postcode_example' => 'LV-1073',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            112 => 
            array (
                'id' => 113,
                'country' => 'MOROCCO',
                'country_code' => 'MA',
                'alpha' => 'MAR',
                'iso' => 504,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'MAD',
                'fedex_route' => 1,
            ),
            113 => 
            array (
                'id' => 114,
                'country' => 'MONACO',
                'country_code' => 'MC',
                'alpha' => 'MCO',
                'iso' => 492,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            114 => 
            array (
                'id' => 115,
                'country' => 'MOLDOVA',
                'country_code' => 'MD',
                'alpha' => 'MDA',
                'iso' => 498,
                'eu' => 0,
                'postal_validation' => '/^[A-Z]{2}\\-[0-9]{4}$/i',
                'postcode_example' => 'MD-2012',
                'currency_code' => 'MDL',
                'fedex_route' => 1,
            ),
            115 => 
            array (
                'id' => 116,
                'country' => 'MADAGASCAR',
                'country_code' => 'MG',
                'alpha' => 'MDG',
                'iso' => 450,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '123',
                'currency_code' => 'MGA',
                'fedex_route' => 1,
            ),
            116 => 
            array (
                'id' => 117,
                'country' => 'MARSHALLISLANDS',
                'country_code' => 'MH',
                'alpha' => 'MHL',
                'iso' => 584,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            117 => 
            array (
                'id' => 118,
                'country' => 'MACEDONIA',
                'country_code' => 'MK',
                'alpha' => 'MKD',
                'iso' => 807,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'MKD',
                'fedex_route' => 1,
            ),
            118 => 
            array (
                'id' => 119,
                'country' => 'MALI',
                'country_code' => 'ML',
                'alpha' => 'MLI',
                'iso' => 466,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            119 => 
            array (
                'id' => 120,
                'country' => 'MYANMAR',
                'country_code' => 'MM',
                'alpha' => 'MMR',
                'iso' => 104,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'MMK',
                'fedex_route' => 1,
            ),
            120 => 
            array (
                'id' => 121,
                'country' => 'MONGOLIA',
                'country_code' => 'MN',
                'alpha' => 'MNG',
                'iso' => 496,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'MNT',
                'fedex_route' => 1,
            ),
            121 => 
            array (
                'id' => 122,
                'country' => 'MACAU',
                'country_code' => 'MO',
                'alpha' => 'MAC',
                'iso' => 446,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'MOP',
                'fedex_route' => 1,
            ),
            122 => 
            array (
                'id' => 123,
                'country' => 'SAIPAN',
                'country_code' => 'MP',
                'alpha' => 'MNP',
                'iso' => 580,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            123 => 
            array (
                'id' => 124,
                'country' => 'MARTINIQUE',
                'country_code' => 'MQ',
                'alpha' => 'MTQ',
                'iso' => 474,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 2,
            ),
            124 => 
            array (
                'id' => 125,
                'country' => 'MAURITANIA',
                'country_code' => 'MR',
                'alpha' => 'MRT',
                'iso' => 478,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'MRO',
                'fedex_route' => 1,
            ),
            125 => 
            array (
                'id' => 126,
                'country' => 'MONTSERRAT',
                'country_code' => 'MS',
                'alpha' => 'MSR',
                'iso' => 500,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            126 => 
            array (
                'id' => 127,
                'country' => 'MALTA',
                'country_code' => 'MT',
                'alpha' => 'MLT',
                'iso' => 470,
                'eu' => 1,
                'postal_validation' => '/^[A-Z]{3}\\ {0,1}[0-9]{4}$/i',
                'postcode_example' => 'VLT 1117',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            127 => 
            array (
                'id' => 128,
                'country' => 'MAURITIUS',
                'country_code' => 'MU',
                'alpha' => 'MUS',
                'iso' => 480,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}[A-Z]{2}[0-9]{3}$/i',
                'postcode_example' => '742CU001',
                'currency_code' => 'MUR',
                'fedex_route' => 1,
            ),
            128 => 
            array (
                'id' => 129,
                'country' => 'MALDIVES',
                'country_code' => 'MV',
                'alpha' => 'MDV',
                'iso' => 462,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'MVR',
                'fedex_route' => 1,
            ),
            129 => 
            array (
                'id' => 130,
                'country' => 'MALAWI',
                'country_code' => 'MW',
                'alpha' => 'MWI',
                'iso' => 454,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'MWK',
                'fedex_route' => 1,
            ),
            130 => 
            array (
                'id' => 131,
                'country' => 'MEXICO',
                'country_code' => 'MX',
                'alpha' => 'MEX',
                'iso' => 484,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'MXN',
                'fedex_route' => 2,
            ),
            131 => 
            array (
                'id' => 132,
                'country' => 'MALAYSIA',
                'country_code' => 'MY',
                'alpha' => 'MYS',
                'iso' => 458,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'MYR',
                'fedex_route' => 1,
            ),
            132 => 
            array (
                'id' => 133,
                'country' => 'MOZAMBIQUE',
                'country_code' => 'MZ',
                'alpha' => 'MOZ',
                'iso' => 508,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'MZN',
                'fedex_route' => 1,
            ),
            133 => 
            array (
                'id' => 134,
                'country' => 'NAMIBIA',
                'country_code' => 'NA',
                'alpha' => 'NAM',
                'iso' => 516,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'ZAR',
                'fedex_route' => 1,
            ),
            134 => 
            array (
                'id' => 135,
                'country' => 'NEWCALEDONIA',
                'country_code' => 'NC',
                'alpha' => 'NCL',
                'iso' => 540,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'XPF',
                'fedex_route' => 1,
            ),
            135 => 
            array (
                'id' => 136,
                'country' => 'NIGER',
                'country_code' => 'NE',
                'alpha' => 'NER',
                'iso' => 562,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            136 => 
            array (
                'id' => 137,
                'country' => 'NIGERIA',
                'country_code' => 'NG',
                'alpha' => 'NGA',
                'iso' => 566,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'NGN',
                'fedex_route' => 1,
            ),
            137 => 
            array (
                'id' => 138,
                'country' => 'NICARAGUA',
                'country_code' => 'NI',
                'alpha' => 'NIC',
                'iso' => 558,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}\\-[0-9]{3}\\-[0-9]{1}$/i',
                'postcode_example' => '050-008-',
                'currency_code' => 'NIO',
                'fedex_route' => 2,
            ),
            138 => 
            array (
                'id' => 139,
                'country' => 'NETHERLANDS',
                'country_code' => 'NL',
                'alpha' => 'NLD',
                'iso' => 528,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}[A-Z]{2}$/i',
                'postcode_example' => '1234AB',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            139 => 
            array (
                'id' => 140,
                'country' => 'NORWAY',
                'country_code' => 'NO',
                'alpha' => 'NOR',
                'iso' => 578,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'NOK',
                'fedex_route' => 1,
            ),
            140 => 
            array (
                'id' => 141,
                'country' => 'NEPAL',
                'country_code' => 'NP',
                'alpha' => 'NPL',
                'iso' => 524,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'NPR',
                'fedex_route' => 1,
            ),
            141 => 
            array (
                'id' => 142,
                'country' => 'NEWZEALAND',
                'country_code' => 'NZ',
                'alpha' => 'NZL',
                'iso' => 554,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'NZD',
                'fedex_route' => 1,
            ),
            142 => 
            array (
                'id' => 143,
                'country' => 'OMAN',
                'country_code' => 'OM',
                'alpha' => 'OMN',
                'iso' => 512,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '123',
                'currency_code' => 'OMR',
                'fedex_route' => 1,
            ),
            143 => 
            array (
                'id' => 144,
                'country' => 'PANAMA',
                'country_code' => 'PA',
                'alpha' => 'PAN',
                'iso' => 591,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            144 => 
            array (
                'id' => 145,
                'country' => 'PERU',
                'country_code' => 'PE',
                'alpha' => 'PER',
                'iso' => 604,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'PEN',
                'fedex_route' => 2,
            ),
            145 => 
            array (
                'id' => 146,
                'country' => 'FRENCHPOLYNESIA',
                'country_code' => 'PF',
                'alpha' => 'PYF',
                'iso' => 258,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'XPF',
                'fedex_route' => 1,
            ),
            146 => 
            array (
                'id' => 147,
                'country' => 'PAPUANEWGUINEA',
                'country_code' => 'PG',
                'alpha' => 'PNG',
                'iso' => 598,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{3}$/i',
                'postcode_example' => '123',
                'currency_code' => 'PGK',
                'fedex_route' => 1,
            ),
            147 => 
            array (
                'id' => 148,
                'country' => 'PHILIPPINES',
                'country_code' => 'PH',
                'alpha' => 'PHL',
                'iso' => 608,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'PHP',
                'fedex_route' => 1,
            ),
            148 => 
            array (
                'id' => 149,
                'country' => 'PAKISTAN',
                'country_code' => 'PK',
                'alpha' => 'PAK',
                'iso' => 586,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'PKR',
                'fedex_route' => 1,
            ),
            149 => 
            array (
                'id' => 150,
                'country' => 'POLAND',
                'country_code' => 'PL',
                'alpha' => 'POL',
                'iso' => 616,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{2}\\-[0-9]{3}$/i',
                'postcode_example' => '00-950',
                'currency_code' => 'PLN',
                'fedex_route' => 1,
            ),
            150 => 
            array (
                'id' => 151,
                'country' => 'PORTUGAL',
                'country_code' => 'PT',
                'alpha' => 'PRT',
                'iso' => 620,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}\\-[0-9]{3}$/i',
                'postcode_example' => '2725-079',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            151 => 
            array (
                'id' => 152,
                'country' => 'PALAU',
                'country_code' => 'PW',
                'alpha' => 'PLW',
                'iso' => 585,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            152 => 
            array (
                'id' => 153,
                'country' => 'PARAGUAY',
                'country_code' => 'PY',
                'alpha' => 'PRY',
                'iso' => 600,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'PYG',
                'fedex_route' => 2,
            ),
            153 => 
            array (
                'id' => 154,
                'country' => 'QATAR',
                'country_code' => 'QA',
                'alpha' => 'QAT',
                'iso' => 634,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'QAR',
                'fedex_route' => 1,
            ),
            154 => 
            array (
                'id' => 155,
                'country' => 'REUNIONISLAND',
                'country_code' => 'RE',
                'alpha' => 'REU',
                'iso' => 638,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            155 => 
            array (
                'id' => 156,
                'country' => 'ROMANIA',
                'country_code' => 'RO',
                'alpha' => 'ROM',
                'iso' => 642,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'RON',
                'fedex_route' => 1,
            ),
            156 => 
            array (
                'id' => 157,
                'country' => 'RUSSIA',
                'country_code' => 'RU',
                'alpha' => 'RUS',
                'iso' => 643,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'RUB',
                'fedex_route' => 1,
            ),
            157 => 
            array (
                'id' => 158,
                'country' => 'RWANDA',
                'country_code' => 'RW',
                'alpha' => 'RWA',
                'iso' => 646,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'RWF',
                'fedex_route' => 1,
            ),
            158 => 
            array (
                'id' => 159,
                'country' => 'SAUDI ARABIA',
                'country_code' => 'SA',
                'alpha' => 'SAU',
                'iso' => 682,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'SAR',
                'fedex_route' => 1,
            ),
            159 => 
            array (
                'id' => 160,
                'country' => 'SEYCHELLES',
                'country_code' => 'SC',
                'alpha' => 'SYC',
                'iso' => 690,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SCR',
                'fedex_route' => 1,
            ),
            160 => 
            array (
                'id' => 161,
                'country' => 'SUDAN',
                'country_code' => 'SD',
                'alpha' => 'SDN',
                'iso' => 736,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SDG',
                'fedex_route' => 1,
            ),
            161 => 
            array (
                'id' => 162,
                'country' => 'SWEDEN',
                'country_code' => 'SE',
                'alpha' => 'SWE',
                'iso' => 752,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'SEK',
                'fedex_route' => 1,
            ),
            162 => 
            array (
                'id' => 163,
                'country' => 'SINGAPORE',
                'country_code' => 'SG',
                'alpha' => 'SGP',
                'iso' => 702,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'SGD',
                'fedex_route' => 1,
            ),
            163 => 
            array (
                'id' => 164,
                'country' => 'SLOVENIA',
                'country_code' => 'SI',
                'alpha' => 'SVN',
                'iso' => 705,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            164 => 
            array (
                'id' => 165,
                'country' => 'SLOVAK REPUBLIC',
                'country_code' => 'SK',
                'alpha' => 'SVK',
                'iso' => 703,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            165 => 
            array (
                'id' => 166,
                'country' => 'SIERRA LEONE',
                'country_code' => 'SL',
                'alpha' => 'SLE',
                'iso' => 694,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SLL',
                'fedex_route' => 1,
            ),
            166 => 
            array (
                'id' => 167,
                'country' => 'SENEGAL',
                'country_code' => 'SN',
                'alpha' => 'SEN',
                'iso' => 686,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            167 => 
            array (
                'id' => 168,
                'country' => 'SURINAME',
                'country_code' => 'SR',
                'alpha' => 'SUR',
                'iso' => 740,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SRD',
                'fedex_route' => 1,
            ),
            168 => 
            array (
                'id' => 169,
                'country' => 'ELSALVADOR',
                'country_code' => 'SV',
                'alpha' => 'SLV',
                'iso' => 222,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            169 => 
            array (
                'id' => 170,
                'country' => 'SYRIA',
                'country_code' => 'SY',
                'alpha' => 'SYR',
                'iso' => 760,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SYP',
                'fedex_route' => 1,
            ),
            170 => 
            array (
                'id' => 171,
                'country' => 'SWAZILAND',
                'country_code' => 'SZ',
                'alpha' => 'SWZ',
                'iso' => 748,
                'eu' => 0,
                'postal_validation' => '/^[A-Z]{1}[0-9]{3}$/i',
                'postcode_example' => 'H100',
                'currency_code' => 'SZL',
                'fedex_route' => 1,
            ),
            171 => 
            array (
                'id' => 172,
                'country' => 'TURKS&CAICOSI',
                'country_code' => 'TC',
                'alpha' => 'TCA',
                'iso' => 796,
                'eu' => 0,
                'postal_validation' => '/^[A-Z]{4}[0-9]{1}[A-Z]{2}$/i',
                'postcode_example' => 'TKCA1ZZ ',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            172 => 
            array (
                'id' => 173,
                'country' => 'CHAD',
                'country_code' => 'TD',
                'alpha' => 'TCD',
                'iso' => 148,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XAF',
                'fedex_route' => 1,
            ),
            173 => 
            array (
                'id' => 174,
                'country' => 'TOGO',
                'country_code' => 'TG',
                'alpha' => 'TGO',
                'iso' => 768,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XOF',
                'fedex_route' => 1,
            ),
            174 => 
            array (
                'id' => 175,
                'country' => 'THAILAND',
                'country_code' => 'TH',
                'alpha' => 'THA',
                'iso' => 764,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'THB',
                'fedex_route' => 1,
            ),
            175 => 
            array (
                'id' => 176,
                'country' => 'TURKMENISTAN',
                'country_code' => 'TM',
                'alpha' => 'TKM',
                'iso' => 795,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'TMT',
                'fedex_route' => 1,
            ),
            176 => 
            array (
                'id' => 177,
                'country' => 'TURKEY',
                'country_code' => 'TR',
                'alpha' => 'TUR',
                'iso' => 792,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'TRY',
                'fedex_route' => 1,
            ),
            177 => 
            array (
                'id' => 178,
                'country' => 'TRINIDAD&TOBAG',
                'country_code' => 'TT',
                'alpha' => 'TTO',
                'iso' => 780,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'TTD',
                'fedex_route' => 2,
            ),
            178 => 
            array (
                'id' => 179,
                'country' => 'TAIWAN',
                'country_code' => 'TW',
                'alpha' => 'TWN',
                'iso' => 158,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'TWD',
                'fedex_route' => 1,
            ),
            179 => 
            array (
                'id' => 180,
                'country' => 'TANZANIA',
                'country_code' => 'TZ',
                'alpha' => 'TZA',
                'iso' => 834,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'TZS',
                'fedex_route' => 1,
            ),
            180 => 
            array (
                'id' => 181,
                'country' => 'UKRAINE',
                'country_code' => 'UA',
                'alpha' => 'UKR',
                'iso' => 804,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'UAH',
                'fedex_route' => 1,
            ),
            181 => 
            array (
                'id' => 182,
                'country' => 'UGANDA',
                'country_code' => 'UG',
                'alpha' => 'UGA',
                'iso' => 800,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'UGX',
                'fedex_route' => 1,
            ),
            182 => 
            array (
                'id' => 183,
                'country' => 'USA',
                'country_code' => 'US',
                'alpha' => 'USA',
                'iso' => 840,
                'eu' => 0,
            'postal_validation' => '/^\\d{5}(-\\d{4})?$/i',
                'postcode_example' => '27833 OR',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            183 => 
            array (
                'id' => 184,
                'country' => 'URUGUAY',
                'country_code' => 'UY',
                'alpha' => 'URY',
                'iso' => 858,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'UYU',
                'fedex_route' => 2,
            ),
            184 => 
            array (
                'id' => 185,
                'country' => 'UZBEKISTAN',
                'country_code' => 'UZ',
                'alpha' => 'UZB',
                'iso' => 860,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'UZS',
                'fedex_route' => 1,
            ),
            185 => 
            array (
                'id' => 186,
                'country' => 'VATICANCITY',
                'country_code' => 'VA',
                'alpha' => 'VAT',
                'iso' => 336,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            186 => 
            array (
                'id' => 187,
                'country' => 'ST VINCENT',
                'country_code' => 'VC',
                'alpha' => 'VCT',
                'iso' => 670,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'XCD',
                'fedex_route' => 2,
            ),
            187 => 
            array (
                'id' => 188,
                'country' => 'VENEZUELA',
                'country_code' => 'VE',
                'alpha' => 'VEN',
                'iso' => 862,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'VEF',
                'fedex_route' => 2,
            ),
            188 => 
            array (
                'id' => 189,
            'country' => 'VIRGINISLANDS(GB)',
                'country_code' => 'VG',
                'alpha' => 'VGB',
                'iso' => 92,
                'eu' => 0,
                'postal_validation' => '/^[A-Z]{2}[0-9]{4}$/i',
                'postcode_example' => 'AB1234',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            189 => 
            array (
                'id' => 190,
            'country' => 'VIRGINISLANDS(US)',
                'country_code' => 'VI',
                'alpha' => 'VIR',
                'iso' => 850,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            190 => 
            array (
                'id' => 191,
                'country' => 'VIETNAM',
                'country_code' => 'VN',
                'alpha' => 'VNM',
                'iso' => 704,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'VND',
                'fedex_route' => 1,
            ),
            191 => 
            array (
                'id' => 192,
                'country' => 'VANUATU',
                'country_code' => 'VU',
                'alpha' => 'VUT',
                'iso' => 548,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'VUV',
                'fedex_route' => 1,
            ),
            192 => 
            array (
                'id' => 193,
                'country' => 'WALLIS&FUTUNA',
                'country_code' => 'WF',
                'alpha' => 'WLF',
                'iso' => 876,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'XPF',
                'fedex_route' => 1,
            ),
            193 => 
            array (
                'id' => 194,
                'country' => 'YEMEN',
                'country_code' => 'YE',
                'alpha' => 'YEM',
                'iso' => 887,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'YER',
                'fedex_route' => 1,
            ),
            194 => 
            array (
                'id' => 195,
                'country' => 'SOUTH AFRICA',
                'country_code' => 'ZA',
                'alpha' => 'ZAF',
                'iso' => 710,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'ZAR',
                'fedex_route' => 1,
            ),
            195 => 
            array (
                'id' => 196,
                'country' => 'ZAMBIA',
                'country_code' => 'ZM',
                'alpha' => 'ZMB',
                'iso' => 894,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'ZMW',
                'fedex_route' => 1,
            ),
            196 => 
            array (
                'id' => 197,
                'country' => 'ZIMBABWE',
                'country_code' => 'ZW',
                'alpha' => 'ZWE',
                'iso' => 716,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'ZWL',
                'fedex_route' => 1,
            ),
            197 => 
            array (
                'id' => 198,
                'country' => 'BOSNIA',
                'country_code' => 'BA',
                'alpha' => 'BIH',
                'iso' => 387,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'BAM',
                'fedex_route' => 1,
            ),
            198 => 
            array (
                'id' => 199,
                'country' => 'TUNISIA',
                'country_code' => 'TN',
                'alpha' => 'TUN',
                'iso' => 788,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{4}$/i',
                'postcode_example' => '1234',
                'currency_code' => 'TND',
                'fedex_route' => 1,
            ),
            199 => 
            array (
                'id' => 200,
                'country' => 'AFGANISTAN',
                'country_code' => 'AF',
                'alpha' => 'AFG',
                'iso' => 4,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AFN',
                'fedex_route' => 1,
            ),
            200 => 
            array (
                'id' => 201,
                'country' => 'IRAN',
                'country_code' => 'IR',
                'alpha' => 'IRN',
                'iso' => 364,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'IRR',
                'fedex_route' => 1,
            ),
            201 => 
            array (
                'id' => 202,
                'country' => 'LIBYA',
                'country_code' => 'LY',
                'alpha' => 'LBY',
                'iso' => 434,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'LYD',
                'fedex_route' => 1,
            ),
            202 => 
            array (
                'id' => 203,
                'country' => 'SERBIA',
                'country_code' => 'RS',
                'alpha' => 'SRB',
                'iso' => 688,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'RSD',
                'fedex_route' => 1,
            ),
            203 => 
            array (
                'id' => 204,
                'country' => 'IND SAMOA',
                'country_code' => 'WS',
                'alpha' => 'WSM',
                'iso' => 882,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'WST',
                'fedex_route' => 2,
            ),
            204 => 
            array (
                'id' => 205,
                'country' => 'TAJIKISTAN',
                'country_code' => 'TJ',
                'alpha' => 'TJK',
                'iso' => 762,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '123456',
                'currency_code' => 'TJS',
                'fedex_route' => 1,
            ),
            205 => 
            array (
                'id' => 206,
                'country' => 'PUERTO RICO',
                'country_code' => 'PR',
                'alpha' => 'PRI',
                'iso' => 630,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            206 => 
            array (
                'id' => 207,
                'country' => 'IRAQ',
                'country_code' => 'IQ',
                'alpha' => 'IRQ',
                'iso' => 368,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'IQD',
                'fedex_route' => 1,
            ),
            207 => 
            array (
                'id' => 208,
                'country' => 'East TIMOR',
                'country_code' => 'TL',
                'alpha' => 'TKL',
                'iso' => 772,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            208 => 
            array (
                'id' => 209,
                'country' => 'CURACAO',
                'country_code' => 'CW',
                'alpha' => 'CUW',
                'iso' => 531,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'ANG',
                'fedex_route' => 1,
            ),
            209 => 
            array (
                'id' => 210,
                'country' => 'BONAIRE',
                'country_code' => 'BQ',
                'alpha' => 'BES',
                'iso' => 535,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 1,
            ),
            210 => 
            array (
                'id' => 211,
                'country' => 'SINT MAARTEN',
                'country_code' => 'SX',
                'alpha' => 'SXM',
                'iso' => 534,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'ANG',
                'fedex_route' => 1,
            ),
            211 => 
            array (
                'id' => 212,
                'country' => 'SAINT MARTIN',
                'country_code' => 'MF',
                'alpha' => 'MAF',
                'iso' => 663,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            212 => 
            array (
                'id' => 213,
                'country' => 'MONTENEGRO',
                'country_code' => 'ME',
                'alpha' => 'MNE',
                'iso' => 499,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            213 => 
            array (
                'id' => 214,
                'country' => 'GUERNSEY',
                'country_code' => 'GG',
                'alpha' => 'GGY',
                'iso' => 831,
                'eu' => 1,
            'postal_validation' => '/^GY[0-9]{1,2}[\\s]*([\\d][A-Za-z]{2})$/i',
                'postcode_example' => 'GY1 4LP',
                'currency_code' => 'GBP',
                'fedex_route' => 1,
            ),
            214 => 
            array (
                'id' => 215,
                'country' => 'JERSEY',
                'country_code' => 'JE',
                'alpha' => 'JEY',
                'iso' => 832,
                'eu' => 1,
            'postal_validation' => '/^JE[0-9]{1,2}[\\s]*([\\d][A-Za-z]{2})$/i',
                'postcode_example' => 'JE2 4LP',
                'currency_code' => 'GBP',
                'fedex_route' => 1,
            ),
            215 => 
            array (
                'id' => 216,
                'country' => 'BRITISH VIRGIN IS',
                'country_code' => 'VG',
                'alpha' => 'VGB',
                'iso' => 128,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'USD',
                'fedex_route' => 2,
            ),
            216 => 
            array (
                'id' => 217,
                'country' => 'KIRIBATI',
                'country_code' => 'KI',
                'alpha' => 'KIR',
                'iso' => 686,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AUD',
                'fedex_route' => 1,
            ),
            217 => 
            array (
                'id' => 218,
                'country' => 'NAURU',
                'country_code' => 'NR',
                'alpha' => 'NRU',
                'iso' => 674,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AUD',
                'fedex_route' => 1,
            ),
            218 => 
            array (
                'id' => 219,
                'country' => 'NIUE',
                'country_code' => 'NU',
                'alpha' => 'NIU',
                'iso' => 683,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'NZD',
                'fedex_route' => 1,
            ),
            219 => 
            array (
                'id' => 220,
                'country' => 'SOLOMON ISLANDS',
                'country_code' => 'SB',
                'alpha' => 'SLB',
                'iso' => 677,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SBD',
                'fedex_route' => 1,
            ),
            220 => 
            array (
                'id' => 221,
                'country' => 'SOMALIA',
                'country_code' => 'SO',
                'alpha' => 'SOM',
                'iso' => 252,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'SOS',
                'fedex_route' => 1,
            ),
            221 => 
            array (
                'id' => 222,
                'country' => 'TONGA',
                'country_code' => 'TO',
                'alpha' => 'TON',
                'iso' => 676,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'TOP',
                'fedex_route' => 1,
            ),
            222 => 
            array (
                'id' => 223,
                'country' => 'TUVALU',
                'country_code' => 'TV',
                'alpha' => 'TUV',
                'iso' => 688,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => 'AUD',
                'fedex_route' => 1,
            ),
            223 => 
            array (
                'id' => 224,
                'country' => 'PALESTINE',
                'country_code' => 'PS',
                'alpha' => 'PSE',
                'iso' => 275,
                'eu' => 0,
                'postal_validation' => '',
                'postcode_example' => '',
                'currency_code' => '',
                'fedex_route' => 1,
            ),
            224 => 
            array (
                'id' => 225,
                'country' => 'CANARY ISLANDS',
                'country_code' => 'IC',
                'alpha' => 'ESP',
                'iso' => 724,
                'eu' => 1,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            225 => 
            array (
                'id' => 226,
                'country' => 'ISLE OF MAN',
                'country_code' => 'IM',
                'alpha' => 'IMN',
                'iso' => 833,
                'eu' => 0,
                'postal_validation' => '/^IM[0-9]{1,2}?\\s?[0-9][A-Z]{2}$/i',
                'postcode_example' => 'IM1 3JT',
                'currency_code' => 'GBP',
                'fedex_route' => 1,
            ),
            226 => 
            array (
                'id' => 227,
                'country' => 'SAN MARINO',
                'country_code' => 'SM',
                'alpha' => 'SAI',
                'iso' => 378,
                'eu' => 1,
                'postal_validation' => '/^4789[0-9]{1}$/i',
                'postcode_example' => '47892',
                'currency_code' => 'EUR',
                'fedex_route' => 1,
            ),
            227 => 
            array (
                'id' => 229,
                'country' => 'NORTH KOREA',
                'country_code' => 'KP',
                'alpha' => 'PRK',
                'iso' => 408,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{6}$/i',
                'postcode_example' => '110110',
                'currency_code' => 'KPW',
                'fedex_route' => 1,
            ),
            228 => 
            array (
                'id' => 230,
                'country' => 'KOSOVO',
                'country_code' => 'XK',
                'alpha' => 'XKX',
                'iso' => 383,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5}$/i',
                'postcode_example' => '12345',
                'currency_code' => 'KWD',
                'fedex_route' => 1,
            ),
            229 => 
            array (
                'id' => 231,
                'country' => 'CUBA',
                'country_code' => 'CU',
                'alpha' => 'CUB',
                'iso' => 192,
                'eu' => 0,
                'postal_validation' => '/^[0-9]{5{$/i',
                'postcode_example' => '12345',
                'currency_code' => 'CUP',
                'fedex_route' => 2,
            ),
        ));
        
        
    }
}