<?php

use Illuminate\Database\Seeder;

class IfsNdPostcodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data[] = ["postcode" => "BT21"];
        $data[] = ["postcode" => "BT22"];
        $data[] = ["postcode" => "BT23 6A"];
        $data[] = ["postcode" => "BT23 6E"];
        $data[] = ["postcode" => "BT23 6L"];
        $data[] = ["postcode" => "BT23 6N"];
        $data[] = ["postcode" => "BT23 6P"];
        $data[] = ["postcode" => "BT23 6Q"];
        $data[] = ["postcode" => "BT23 6R"];
        $data[] = ["postcode" => "BT23 6S"];
        $data[] = ["postcode" => "BT23 6T"];
        $data[] = ["postcode" => "BT23 6U"];
        $data[] = ["postcode" => "BT25 1E"];
        $data[] = ["postcode" => "BT25 1G"];
        $data[] = ["postcode" => "BT25 1H"];
        $data[] = ["postcode" => "BT25 1J"];
        $data[] = ["postcode" => "BT25 1L"];
        $data[] = ["postcode" => "BT25 1N"];
        $data[] = ["postcode" => "BT25 1Q"];
        $data[] = ["postcode" => "BT25 1R"];
        $data[] = ["postcode" => "BT25 1S"];
        $data[] = ["postcode" => "BT25 1U"];
        $data[] = ["postcode" => "BT25 2"];
        $data[] = ["postcode" => "BT25 6"];
        $data[] = ["postcode" => "BT30 7"];
        $data[] = ["postcode" => "BT30 9G"];
        $data[] = ["postcode" => "BT30 9H"];
        $data[] = ["postcode" => "BT30 9J"];
        $data[] = ["postcode" => "BT30 9L"];
        $data[] = ["postcode" => "BT30 9N"];
        $data[] = ["postcode" => "BT30 9P"];
        $data[] = ["postcode" => "BT30 9Q"];
        $data[] = ["postcode" => "BT30 9R"];
        $data[] = ["postcode" => "BT30 9S"];
        $data[] = ["postcode" => "BT30 9T"];
        $data[] = ["postcode" => "BT30 9U"];
        $data[] = ["postcode" => "BT31 9F"];
        $data[] = ["postcode" => "BT31 9L"];
        $data[] = ["postcode" => "BT31 9P"];
        $data[] = ["postcode" => "BT31 9Q"];
        $data[] = ["postcode" => "BT31 9R"];
        $data[] = ["postcode" => "BT31 9S"];
        $data[] = ["postcode" => "BT31 9T"];
        $data[] = ["postcode" => "BT31 9U"];
        $data[] = ["postcode" => "BT32 5"];
        $data[] = ["postcode" => "BT34 1F"];
        $data[] = ["postcode" => "BT34 1N"];
        $data[] = ["postcode" => "BT34 1P"];
        $data[] = ["postcode" => "BT34 1R"];
        $data[] = ["postcode" => "BT34 1S"];
        $data[] = ["postcode" => "BT34 1T"];
        $data[] = ["postcode" => "BT34 2B"];
        $data[] = ["postcode" => "BT34 2E"];
        $data[] = ["postcode" => "BT34 2F"];
        $data[] = ["postcode" => "BT34 2G"];
        $data[] = ["postcode" => "bt34 2h"];
        $data[] = ["postcode" => "BT34 2J"];
        $data[] = ["postcode" => "BT34 2N"];
        $data[] = ["postcode" => "BT34 2R"];
        $data[] = ["postcode" => "BT34 2S"];
        $data[] = ["postcode" => "BT34 3B"];
        $data[] = ["postcode" => "BT34 3G"];
        $data[] = ["postcode" => "BT34 3H"];
        $data[] = ["postcode" => "BT34 3J"];
        $data[] = ["postcode" => "BT34 3L"];
        $data[] = ["postcode" => "BT34 3N"];
        $data[] = ["postcode" => "BT34 3P"];
        $data[] = ["postcode" => "BT34 3Q"];
        $data[] = ["postcode" => "BT34 3R"];
        $data[] = ["postcode" => "BT34 3T"];
        $data[] = ["postcode" => "BT34 3U"];
        $data[] = ["postcode" => "BT34 3X"];
        $data[] = ["postcode" => "BT34 5"];
        $data[] = ["postcode" => "BT35 0"];
        $data[] = ["postcode" => "BT35 6R"];
        $data[] = ["postcode" => "BT35 6T"];
        $data[] = ["postcode" => "BT35 7P"];
        $data[] = ["postcode" => "BT35 7Q"];
        $data[] = ["postcode" => "BT35 8J"];
        $data[] = ["postcode" => "BT35 8L"];
        $data[] = ["postcode" => "BT35 9"];
        $data[] = ["postcode" => "BT41 3JR"];
        $data[] = ["postcode" => "BT44 0"];
        $data[] = ["postcode" => "BT44 8E"];
        $data[] = ["postcode" => "BT44 8H"];
        $data[] = ["postcode" => "BT44 8P"];
        $data[] = ["postcode" => "BT44 8Q"];
        $data[] = ["postcode" => "BT44 8R"];
        $data[] = ["postcode" => "BT44 8S"];
        $data[] = ["postcode" => "BT44 8T"];
        $data[] = ["postcode" => "BT45 5G"];
        $data[] = ["postcode" => "BT45 5H"];
        $data[] = ["postcode" => "BT45 5J"];
        $data[] = ["postcode" => "BT45 5L"];
        $data[] = ["postcode" => "BT45 5N"];
        $data[] = ["postcode" => "BT45 5P"];
        $data[] = ["postcode" => "BT45 5Q"];
        $data[] = ["postcode" => "BT45 5R"];
        $data[] = ["postcode" => "BT45 5S"];
        $data[] = ["postcode" => "BT45 6G"];
        $data[] = ["postcode" => "BT45 6H"];
        $data[] = ["postcode" => "BT45 6J"];
        $data[] = ["postcode" => "BT45 6L"];
        $data[] = ["postcode" => "BT45 6N"];
        $data[] = ["postcode" => "BT45 6Q"];
        $data[] = ["postcode" => "BT45 7A"];
        $data[] = ["postcode" => "BT45 7B"];
        $data[] = ["postcode" => "BT45 7D"];
        $data[] = ["postcode" => "BT45 7E"];
        $data[] = ["postcode" => "BT45 7F"];
        $data[] = ["postcode" => "BT45 7H"];
        $data[] = ["postcode" => "BT45 7J"];
        $data[] = ["postcode" => "BT45 7L"];
        $data[] = ["postcode" => "BT45 7X"];
        $data[] = ["postcode" => "BT45 8"];
        $data[] = ["postcode" => "BT47 4B"];
        $data[] = ["postcode" => "BT47 5ST"];
        $data[] = ["postcode" => "BT51 4DG"];
        $data[] = ["postcode" => "BT53 8B"];
        $data[] = ["postcode" => "BT54 6"];
        $data[] = ["postcode" => "BT55 7D"];
        $data[] = ["postcode" => "BT56 8T"];
        $data[] = ["postcode" => "BT57"];
        $data[] = ["postcode" => "bt60 3h"];
        $data[] = ["postcode" => "BT68"];
        $data[] = ["postcode" => "BT69"];
        $data[] = ["postcode" => "BT70 1P"];
        $data[] = ["postcode" => "BT70 1Q"];
        $data[] = ["postcode" => "BT70 1R"];
        $data[] = ["postcode" => "BT70 1S"];
        $data[] = ["postcode" => "BT70 1T"];
        $data[] = ["postcode" => "BT70 2H"];
        $data[] = ["postcode" => "BT70 2J"];
        $data[] = ["postcode" => "BT70 2N"];
        $data[] = ["postcode" => "BT70 2P"];
        $data[] = ["postcode" => "BT70 2Q"];
        $data[] = ["postcode" => "BT70 2R"];
        $data[] = ["postcode" => "BT70 2S"];
        $data[] = ["postcode" => "BT70 2T"];
        $data[] = ["postcode" => "BT70 2U"];
        $data[] = ["postcode" => "BT70 3"];
        $data[] = ["postcode" => "BT71 4Q"];
        $data[] = ["postcode" => "BT71 5"];
        $data[] = ["postcode" => "BT74 5"];
        $data[] = ["postcode" => "BT74 8"];
        $data[] = ["postcode" => "BT74 9"];
        $data[] = ["postcode" => "BT77 0B"];
        $data[] = ["postcode" => "BT77 0D"];
        $data[] = ["postcode" => "BT77 0E"];
        $data[] = ["postcode" => "BT77 0H"];
        $data[] = ["postcode" => "BT78 1N"];
        $data[] = ["postcode" => "BT78 1P"];
        $data[] = ["postcode" => "BT78 1R"];
        $data[] = ["postcode" => "BT78 1S"];
        $data[] = ["postcode" => "BT78 1T"];
        $data[] = ["postcode" => "BT78 1U"];
        $data[] = ["postcode" => "BT78 2R"];
        $data[] = ["postcode" => "BT78 2S"];
        $data[] = ["postcode" => "BT78 3"];
        $data[] = ["postcode" => "BT78 4"];
        $data[] = ["postcode" => "BT78 5"];
        $data[] = ["postcode" => "BT79 0H"];
        $data[] = ["postcode" => "BT79 0J"];
        $data[] = ["postcode" => "BT79 0L"];
        $data[] = ["postcode" => "BT79 0P"];
        $data[] = ["postcode" => "BT79 0Q"];
        $data[] = ["postcode" => "BT79 0R"];
        $data[] = ["postcode" => "BT79 0S"];
        $data[] = ["postcode" => "BT79 0T"];
        $data[] = ["postcode" => "BT79 0U"];
        $data[] = ["postcode" => "BT79 0X"];
        $data[] = ["postcode" => "BT79 0Y"];
        $data[] = ["postcode" => "BT79 7P"];
        $data[] = ["postcode" => "BT79 7Q"];
        $data[] = ["postcode" => "BT79 7R"];
        $data[] = ["postcode" => "BT79 7S"];
        $data[] = ["postcode" => "BT79 7T"];
        $data[] = ["postcode" => "BT79 7U"];
        $data[] = ["postcode" => "BT79 8"];
        $data[] = ["postcode" => "BT79 9"];
        $data[] = ["postcode" => "BT79 9H"];
        $data[] = ["postcode" => "BT80 0"];
        $data[] = ["postcode" => "BT80 8R"];
        $data[] = ["postcode" => "BT80 8S"];
        $data[] = ["postcode" => "BT80 8U"];
        $data[] = ["postcode" => "BT80 8X"];
        $data[] = ["postcode" => "BT80 9B"];
        $data[] = ["postcode" => "BT80 9D"];
        $data[] = ["postcode" => "BT80 9E"];
        $data[] = ["postcode" => "BT80 9J"];
        $data[] = ["postcode" => "BT80 9N"];
        $data[] = ["postcode" => "BT80 9P"];
        $data[] = ["postcode" => "BT80 9Q"];
        $data[] = ["postcode" => "BT80 9S"];
        $data[] = ["postcode" => "BT80 9T"];
        $data[] = ["postcode" => "BT80 9U"];
        $data[] = ["postcode" => "BT80 9X"];
        $data[] = ["postcode" => "BT81"];
        $data[] = ["postcode" => "BT82 0"];
        $data[] = ["postcode" => "BT82 8F"];
        $data[] = ["postcode" => "BT82 8L"];
        $data[] = ["postcode" => "BT82 8NU"];
        $data[] = ["postcode" => "BT82 8P"];
        $data[] = ["postcode" => "BT82 8Q"];
        $data[] = ["postcode" => "BT82 8T"];
        $data[] = ["postcode" => "BT82 9F"];
        $data[] = ["postcode" => "BT82 9G"];
        $data[] = ["postcode" => "BT82 9J"];
        $data[] = ["postcode" => "BT82 9L"];
        $data[] = ["postcode" => "BT82 9N"];
        $data[] = ["postcode" => "BT82 9Q"];
        $data[] = ["postcode" => "BT82 9R"];
        $data[] = ["postcode" => "BT82 9S"];
        $data[] = ["postcode" => "BT82 9T"];
        $data[] = ["postcode" => "BT92 0A"];
        $data[] = ["postcode" => "BT92 0B"];
        $data[] = ["postcode" => "BT92 0D"];
        $data[] = ["postcode" => "BT92 0E"];
        $data[] = ["postcode" => "BT92 0F"];
        $data[] = ["postcode" => "BT92 0H"];
        $data[] = ["postcode" => "BT92 0J"];
        $data[] = ["postcode" => "BT92 0N"];
        $data[] = ["postcode" => "BT92 0P"];
        $data[] = ["postcode" => "BT92 0Q"];
        $data[] = ["postcode" => "BT92 0R"];
        $data[] = ["postcode" => "BT92 1F"];
        $data[] = ["postcode" => "BT92 2"];
        $data[] = ["postcode" => "BT92 3"];
        $data[] = ["postcode" => "BT92 4"];
        $data[] = ["postcode" => "BT92 6"];
        $data[] = ["postcode" => "BT92 7"];
        $data[] = ["postcode" => "BT92 8"];
        $data[] = ["postcode" => "BT92 9"];
        $data[] = ["postcode" => "BT93"];
        $data[] = ["postcode" => "BT94"];
        $data[] = ["postcode" => "BT94 2"];
        $data[] = ["postcode" => "BT94 3"];
        $data[] = ["postcode" => "BT94 4"];
        $data[] = ["postcode" => "BT94 5"];

        // Modify a few records
        DB::table('ifs_nd_postcodes')->insert($data);
    }
}
