<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace App\ScsXml;

/**
 * Description of RecJny
 *
 * @author gmcbroom
 */
class RecJny extends SCSTable {

    public function __construct() {

        $this->tableName = "rec-jny";

        $this->attributes = [
			"airline-prefix" => "",
			"arr-date-1" => "",
			"arr-date-2" => "",
			"arr-date-3" => "",
			"arr-date-4" => "",
			"arr-date-5" => "",
			"arr-date-6" => "",
			"arr-time-1" => "",
			"arr-time-2" => "",
			"arr-time-3" => "",
			"arr-time-4" => "",
			"arr-time-5" => "",
			"arr-time-6" => "",
			"car-code-1" => "",
			"car-code-2" => "",
			"car-code-3" => "",
			"car-code-4" => "",
			"car-code-5" => "",
			"car-code-6" => "",
			"car-desc-1" => "",
			"car-desc-2" => "",
			"car-desc-3" => "",
			"car-desc-4" => "",
			"car-desc-5" => "",
			"car-desc-6" => "",
			"char-prefix" => "",
			"date-idx1" => "",
			"dept-date-1" => "",
			"dept-date-2" => "",
			"dept-date-3" => "",
			"dept-date-4" => "",
			"dept-date-5" => "",
			"dept-date-6" => "",
			"dept-time-1" => "",
			"dept-time-2" => "",
			"dept-time-3" => "",
			"dept-time-4" => "",
			"dept-time-5" => "",
			"dept-time-6" => "",
			"dv-car-curr" => "",
			"dv-carriage" => "",
			"dv-cus-curr" => "",
			"dv-customs" => "",
			"eda" => "",
			"eta" => "",
			"ext-code-1" => "",
			"ext-code-2" => "",
			"ext-code-3" => "",
			"ext-code-4" => "",
			"ext-code-5" => "",
			"ext-code-6" => "",
			"ext-date-1" => "",
			"ext-date-2" => "",
			"ext-date-3" => "",
			"ext-date-4" => "",
			"ext-date-5" => "",
			"ext-date-6" => "",
			"ext-desc-1" => "",
			"ext-desc-2" => "",
			"ext-desc-3" => "",
			"ext-desc-4" => "",
			"ext-desc-5" => "",
			"ext-desc-6" => "",
			"flight-by-1" => "",
			"flight-by-2" => "",
			"flight-by-3" => "",
			"flight-date-1" => "",
			"flight-date-2" => "",
			"flight-idx1" => "",
			"flight-idx2" => "",
			"flight-idx3" => "",
			"flight-idx4" => "",
			"flight-idx5" => "",
			"flight-no-1" => "",
			"flight-no-2" => "",
			"flight-prefix-1" => "",
			"flight-prefix-2" => "",
			"flight-time-1" => "",
			"flight-time-2" => "",
			"flight-time-3" => "",
			"flight-to-1" => "",
			"flight-to-2" => "",
			"flight-to-3" => "",
			"insurance" => "",
			"jny-code-1" => "",
			"jny-code-2" => "",
			"jny-code-3" => "",
			"jny-code-4" => "",
			"jny-code-5" => "",
			"jny-code-6" => "",
			"jny-desc-1" => "",
			"jny-desc-2" => "",
			"jny-desc-3" => "",
			"jny-desc-4" => "",
			"jny-desc-5" => "",
			"jny-desc-6" => "",
			"loc-code-1" => "",
			"loc-code-2" => "",
			"loc-code-3" => "",
			"loc-code-4" => "",
			"loc-code-5" => "",
			"loc-code-6" => "",
			"loc-desc-1" => "",
			"loc-desc-2" => "",
			"loc-desc-3" => "",
			"loc-desc-4" => "",
			"loc-desc-5" => "",
			"loc-desc-6" => "",
			"mawb" => "",
			"mawb-clerk" => "",
			"mawb-date" => "",
			"port-of-discharge" => "",
			"port-of-loading" => "",
			"rec-id" => "",
			"record-link" => "",
			"third-flight-date" => "",
			"third-flight-no" => "",
			"third-flight-prefix" => "",
			"truck-leg" => "",
        ];
    }

}
